export { useLessonsApi } from '~/composables/api/useLessonsApi'
export { useStudentsApi } from '~/composables/api/useStudentsApi'
export { useStudentsGroupsApi } from '~/composables/api/useStudentsGroups'
export { useSubjectsApi } from '~/composables/api/useSubjectsApi'
export { useTeachersApi } from '~/composables/api/useTeachersApi'
